# Generated by Django 4.1.5 on 2023-02-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
