# Generated by Django 4.1.5 on 2023-02-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0002_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='product_image',
        ),
    ]
