# Generated by Django 4.1.5 on 2023-02-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0004_card_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regmodel',
        ),
    ]
